services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konser_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - konser_network

  db:
    image: mysql:8
    container_name: konser_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: team_2_reservasi_tiket_konser
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - konser_network

  redis:
    image: redis:7-alpine
    container_name: konser_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - konser_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: konser_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - konser_network

networks:
  konser_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
